[app_settings]
app_version = "0.1.0"
app_name = "image cloude"
app_host = "0.0.0.0"
app_port = 8000


[db_settings]
db_name = "postgres"
db_user = "user"
db_password = "pass"
db_host = "localhost"
db_port = 5432

# главный пользователь - postgres, пароль либо pass либо password
# видимо так postgres:pass